In [1]:
import numpy as np
import pennylane as qml

# I.1 All about qubits

In [2]:
# vector representations of |0> and |1>
ket_0 = np.array([1, 0]) 
ket_1 = np.array([0, 1])

## Codercise I.1.1

In [3]:
def normalize_state(alpha, beta):
    """
    returns: 
        array[complex]: normalized quantum state as a 2d array
    ****************
    alpha (complex), beta (complex): amplitudes for states |0>, |1> respectively
    """
    # compute normalization factor (i.e. the Euclidean norm)
    norm = np.sqrt(np.abs(alpha)**2 + np.abs(beta)**2)
    return 1/norm * (alpha * ket_0 + beta * ket_1)
    

In [4]:
# example:
alpha = 2.0 + 1.0j
beta = -0.3 + 0.4j
normalize_state(alpha, beta)

array([ 0.87287156+0.43643578j, -0.13093073+0.17457431j])

## Codercise I.1.2

In [5]:
def inner_product(state_1, state_2):
    """
    returns: 
        complex: inner product between two states
    ****************
    state_1 (array[complex]), state_2 (array[complex]): quantum state vectors
    """
    return np.sum([np.conj(a) * b for a, b in zip(state_1, state_2)])


In [6]:
# test that |0> |1> form an orthonormal basis
print(f"<0|0> = {inner_product(ket_0, ket_0)}")
print(f"<0|1> = {inner_product(ket_0, ket_1)}")
print(f"<1|0> = {inner_product(ket_1, ket_0)}")
print(f"<1|1> = {inner_product(ket_1, ket_1)}")


<0|0> = 1
<0|1> = 0
<1|0> = 0
<1|1> = 1


In [7]:
# example:
state_1 = np.array([0.8, 0.6])
state_2 = np.array([1 / np.sqrt(2), 1j / np.sqrt(2)]) 
inner_product(state_1, state_2)

(0.565685424949238+0.42426406871192845j)

## Codercise I.1.3

In [8]:
def measure_state(state, num_meas):
    """
    returns: 
        array[int]: (num_meas)-dimensional array of quantum measurements
    ****************
    state (array[complex]): normalized quantum state vector
    num_meas (int): the number of measurements to be taken
    """
    meas = np.random.choice([0, 1], p=[np.abs(a)**2 for a in state], size=num_meas)
    return meas


In [9]:
# example:
state = np.array([0.8, 0.6])
measure_state(state, 10)

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 0])

## Codercise I.1.4

In [10]:
def apply_u(state):
    """
    returns: 
        array[complex]: result of quantum operation U on state
    ****************
    state (array[complex]): normalized quantum state vector
    """
    return (U @ state)
    

In [11]:
# example:
U = np.array([[0, 1], [1, 0]])
state = np.array([0.8, 0.6])
apply_u(state)

array([0.6, 0.8])

## Codercise I.1.5

In [12]:
def initialize_state():
    """
    returns: 
        array[float]: vector for state |0>
    """
    return np.array([1,0])


def quantum_algorithm():
    """
    returns: 
        array[int]: array of 100 measurements
    """
    new_state = apply_u(initialize_state())
    return measure_state(new_state, 100)


In [13]:
# example:
U = np.array([[1, 1], [1, -1]]) / np.sqrt(2)
quantum_algorithm()

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1])